<?php

namespace DiplomBundle\Repository;

/**
 * WorkerRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkerRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
